name: Build iOS Client Dylib

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # macOS üzerinde iOS SDK clang araçlarıyla dylib'i derler
    - name: Build Tweak Dylib
      run: |
        make

    # Derlenen dylib dosyasını indirilebilir artifact olarak yükler
    - name: Upload Compiled Binary
      uses: actions/upload-artifact@v4
      with:
        name: ytpavlov_mc_ios_dylib
        path: ytpavlov_mc_ios.dylib
